package org.gusdb.fgputil.db.wrapper;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

public class AbstractStatementWrapper implements Statement {

  protected final Statement _underlyingStatement;

  protected AbstractStatementWrapper(Statement underlyingStatement) {
    _underlyingStatement = underlyingStatement;
  }

  @Override
  public Connection getConnection() throws SQLException {
    return _underlyingStatement.getConnection();
  }

  @Override
  public ResultSet getGeneratedKeys() throws SQLException {
    return _underlyingStatement.getGeneratedKeys();
  }

  @Override
  public ResultSet getResultSet() throws SQLException {
    return _underlyingStatement.getResultSet();
  }

  @Override
  public ResultSet executeQuery(String sql) throws SQLException {
    return _underlyingStatement.executeQuery(sql);
  }

  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    return _underlyingStatement.unwrap(iface);
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) throws SQLException {
    return _underlyingStatement.isWrapperFor(iface);
  }

  @Override
  public int executeUpdate(String sql) throws SQLException {
    return _underlyingStatement.executeUpdate(sql);
  }

  @Override
  public void close() throws SQLException {
    _underlyingStatement.close();
  }

  @Override
  public int getMaxFieldSize() throws SQLException {
    return _underlyingStatement.getMaxFieldSize();
  }

  @Override
  public void setMaxFieldSize(int max) throws SQLException {
    _underlyingStatement.setMaxFieldSize(max);
  }

  @Override
  public int getMaxRows() throws SQLException {
    return _underlyingStatement.getMaxRows();
  }

  @Override
  public void setMaxRows(int max) throws SQLException {
    _underlyingStatement.setMaxRows(max);
  }

  @Override
  public void setEscapeProcessing(boolean enable) throws SQLException {
    _underlyingStatement.setEscapeProcessing(enable);
  }

  @Override
  public int getQueryTimeout() throws SQLException {
    return _underlyingStatement.getQueryTimeout();
  }

  @Override
  public void setQueryTimeout(int seconds) throws SQLException {
    _underlyingStatement.setQueryTimeout(seconds);
  }

  @Override
  public void cancel() throws SQLException {
    _underlyingStatement.cancel();
  }

  @Override
  public SQLWarning getWarnings() throws SQLException {
    return _underlyingStatement.getWarnings();
  }

  @Override
  public void clearWarnings() throws SQLException {
    _underlyingStatement.clearWarnings();
  }

  @Override
  public void setCursorName(String name) throws SQLException {
    _underlyingStatement.setCursorName(name);
  }

  @Override
  public boolean execute(String sql) throws SQLException {
    return _underlyingStatement.execute(sql);
  }

  @Override
  public int getUpdateCount() throws SQLException {
    return _underlyingStatement.getUpdateCount();
  }

  @Override
  public boolean getMoreResults() throws SQLException {
    return _underlyingStatement.getMoreResults();
  }

  @Override
  public void setFetchDirection(int direction) throws SQLException {
    _underlyingStatement.setFetchDirection(direction);
  }

  @Override
  public int getFetchDirection() throws SQLException {
    return _underlyingStatement.getFetchDirection();
  }

  @Override
  public void setFetchSize(int rows) throws SQLException {
    _underlyingStatement.setFetchSize(rows);
  }

  @Override
  public int getFetchSize() throws SQLException {
    return _underlyingStatement.getFetchSize();
  }

  @Override
  public int getResultSetConcurrency() throws SQLException {
    return _underlyingStatement.getResultSetConcurrency();
  }

  @Override
  public int getResultSetType() throws SQLException {
    return _underlyingStatement.getResultSetType();
  }

  @Override
  public void addBatch(String sql) throws SQLException {
    _underlyingStatement.addBatch(sql);
  }

  @Override
  public void clearBatch() throws SQLException {
    _underlyingStatement.clearBatch();
  }

  @Override
  public int[] executeBatch() throws SQLException {
    return _underlyingStatement.executeBatch();
  }

  @Override
  public boolean getMoreResults(int current) throws SQLException {
    return _underlyingStatement.getMoreResults(current);
  }

  @Override
  public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    return _underlyingStatement.executeUpdate(sql, autoGeneratedKeys);
  }

  @Override
  public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
    return _underlyingStatement.executeUpdate(sql, columnIndexes);
  }

  @Override
  public int executeUpdate(String sql, String[] columnNames) throws SQLException {
    return _underlyingStatement.executeUpdate(sql, columnNames);
  }

  @Override
  public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
    return _underlyingStatement.execute(sql, autoGeneratedKeys);
  }

  @Override
  public boolean execute(String sql, int[] columnIndexes) throws SQLException {
    return _underlyingStatement.execute(sql, columnIndexes);
  }

  @Override
  public boolean execute(String sql, String[] columnNames) throws SQLException {
    return _underlyingStatement.execute(sql, columnNames);
  }

  @Override
  public int getResultSetHoldability() throws SQLException {
    return _underlyingStatement.getResultSetHoldability();
  }

  @Override
  public boolean isClosed() throws SQLException {
    return _underlyingStatement.isClosed();
  }

  @Override
  public void setPoolable(boolean poolable) throws SQLException {
    _underlyingStatement.setPoolable(poolable);
  }

  @Override
  public boolean isPoolable() throws SQLException {
    return _underlyingStatement.isPoolable();
  }

  @Override
  public void closeOnCompletion() throws SQLException {
    _underlyingStatement.closeOnCompletion();
  }

  @Override
  public boolean isCloseOnCompletion() throws SQLException {
    return _underlyingStatement.isCloseOnCompletion();
  }

}
